     <h2 class="page_title">Demander le Titre Ici</h2>
   
     <p class="normal">Tout votre contenu de page ira ici. Ceci est un paragraphe normal, est ici un <a href="#">lien</a>.</p>
   
     <p class="quoted">Un exemple d'un paragraphe cit&eacute;, est ici un <a href="#">lien</a>.</p>
     
     <h3 class="sub_title">Sous Intituler</h3>
     
     <p class="normal">Ceci est un paragraphe normal, et <span class="note">ceci est une note - est ici un <a href="#">lien</a>.</span></p>