     <h2 class="page_title">Rooep Titel Hier op</h2>
   
     <p class="normal">Alle uw pagina inhoud zal hier gaan. Dit is een normale paragraaf, hier is een <a href="#">De schakel</a>.</p>
   
     <p class="quoted">Een voorbeeld van een geciteerde paragraaf, hier is een <a href="#">De schakel</a>.</p>
     
     <h3 class="sub_title">Sub Titel</h3>
     
     <p class="normal">Dit is een normale paragraaf en <span class="note">Dit is een aantekening - hier is een <a href="#">De schakel</a>.</span></span></p>
