    <a href="http://www.loquacity.info">Project Home</a> &bull;
    <a href="http://bugs.loquacity.info" title="File and View bugs">Issue Tracker</a> &bull;
    <a href="http://forum.loquacity.info" title="Community Discussion">Community Forums</a> &bull;
    <a href="https://developer.berlios.de/project/showfiles.php?group_id=6761&release_id=10163">Downloads</a> <!--&bull;
    <a href="#" title="Sorry, nothing online yet">Documentation</a> //-->